# Generated by Django 4.0.2 on 2022-05-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_addminsion_number_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='addminsion_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
