# Generated by Django 4.0.2 on 2022-05-07 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_description_club_name'),
        ('users', '0003_alter_user_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='addminsion_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('year', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=10)),
                ('addminsion_number', models.CharField(max_length=100, unique=True)),
                ('branch', models.CharField(max_length=20)),
                ('profile_pics', models.ImageField(upload_to='users/media/profilepics')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
