# Generated by Django 4.0.2 on 2022-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_addminsion_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_pic',
            field=models.ImageField(default='default.jpg', upload_to='backgroundpics'),
        ),
    ]
